### PR TITLE
Adding ability to create and link secrets in projects

### PR DESCRIPTION
**Pull request by etsauer**
#### What does this PR do?
Creates kube secrets from local files

#### Which tests illustrate how this code works?
Need some input on how best to handle this & how/where we want to read in local files from. My test scenario looks something like:

```
						"secrets": [
							{
								"name": "mysecret1",
								"link_to_serviceaccounts": [
									{
										"sa_name": "default"
									}
								],
								"files": [
									{
										"name": "myfile",
										"path": "/root/repository/ansible-stacks/myfile"
									}
								]
							}
						],
```

#### Is there a relevant Issue open for this?
n/a

#### Are there any other relevant resources that should be reviewed as well?
n/a

#### Who would you like to review this?
/cc @oybed @sherl0cks

### CODE REVIEW

**Comment by sherl0cks** [comment]
@etsauer Thanks for sending in another changeset. I want to take a quick second to talk process. This is a good example as to why the labs team usually starts writing a new feature by modelling the object definition in https://github.com/rht-labs/api-design, before writing code/ansible. With that said, we're very thankful to have you collaborating in this space so we don't want to increase the process overhead for you. Unless you would like take on the burden of making swagger spec changes, as well the multitude of downstream impacts associated with that (you don't, trust me), we've agreed as a team to bring in your changes as private features of the stacks repo, and then bring them out into our public API (via the swagger spec) as the core team's schedule allows.

It's still important to do this object modelling as you've pointed out, so here are my thoughts there:

- To make this explicit, `secrets` would be a field of a `project`. It would be an array of object type `Secret`.
- `link_to_serviceaccounts` can be a simple list of strings. In general, it's best to avoid create new objects unless it's really necessary, as this increases complexity in other parts of the system, as well as makes the JSON harder to read. Below is an example of an array of string for `link_to_serviceaccounts`:
```
"link_to_serviceaccounts" : [
  "foo",
  "bar",
  "baz"  
] 
```

Further question to flesh out the `files` part of the model:

- do we need to handle the `oc secrets new` scenario where you point to a directory?
- is it important to support custom secret names?

**Comment by etsauer** [comment]
@sherl0cks ok, I think i understand here that I need to update my service account handling to make it a simple string field. will do.

To your questions about the files model,

- I don't have a need to load secrets from a directory, but if you see I need for it I can add/test it. I believe it will work as-is
- my custom secret names, are you referring to a data structure like:

```
"files": [
	{
		"/root/repository/ansible-stacks/myfile"
	}
]
```
as opposed to:
```
"files": [
	{
		"name": "myfile",
		"path": "/root/repository/ansible-stacks/myfile"
	}
]
```

If yes, I see some value in behind able to affect the name of the file, as it dictates the file name the data will be mounted as in the pod, so being able to control that is useful to some.

**Comment by etsauer** [comment]
my bad, directory will not work while passing a key, so it will not work as-is. perhaps that's a good reason to remove the custom key alltogether. i'll think about that a bit more tonight.

**Comment by etsauer** [comment]
@sherl0cks ok, updated to simplify the models. My test case now looks like:
```
"secrets": [
	{
		"name": "mysecret1",
		"link_to_serviceaccounts": [
			"default",
			"builder"
		],
		"files": [
			"/root/repository/ansible-stacks/myfile"
		]
	}
],
```

**Comment by etsauer** [comment]
I think the last piece is probably coming up with a valid test playbook that puts files somewhere. Do you or @oybed have any thoughts on how best to handle that?

**Comment by etsauer** [comment]
@sherl0cks test case added.

**Comment by etsauer** [comment]
bump. any feedback here?

**Comment by etsauer** [comment]
@sherl0cks @oybed I've added some functionality here that affects the api model slightly. We had a need to be able to update a secret with new values, so i've added an overwrite option to the secrets object definition:

```
"secrets": [
	{
		"name": "mysecret1",
		"link_to_serviceaccounts": [
			"default",
			"builder"
		],
		"files": [
			"/root/repository/ansible-stacks/myfile"
		],
                "overwrite": "True"
	}
],
```

On the ansible side, i've set it up so that any value other than "False" results in a "True"

**Pull request closed without merging**
