### PR TITLE
adding support for custom service / route / dc port spec

### PR DESCRIPTION
**Pull request by sherl0cks**
#### What does this PR do?

Supports the creation of custom routes / services / port specs on dc's. Enables ssl via tls passthrough routes.
#### Which tests illustrate how this code works?

`cdk` tests updated to use new approach.

two poorly named tests (I'm in a hurry here) added as a sort of unit test for the single task file. Both are prefixed with `networking`
#### Is there a relevant Issue open for this?

None right now
#### Are there any other relevant resources that should be reviewed as well?

Lots of use of  [filter plugins](http://docs.ansible.com/ansible/developing_plugins.html#filter-plugins). These are extremely useful for complicated manipulated of JSON where you really need imperative code. I have opened #40 to move the code base to this approach.
#### Who would you like to review this?

/cc @oybed @mdanter

### CODE REVIEW

**Comment by oybed** [comment]
Looked it over and looks like it should work. I'll give it a try tomorrow.

**Comment by oybed** [comment]
@sherl0cks seeing the following error when running with this change - it has happened a few times in a row, so don't think it was just a fluke. Thoughts?

```
TASK [create-openshift-resources : Set Fact for DC object] *********************
ok: [localhost] => {"ansible_facts": {"dc": {"apiVersion": "v1", "kind": "DeploymentConfig", "metadata": {"annotations": {"openshift.io/generated-by": "OpenShiftNewApp"}, "creationTimestamp": "2016-10-20T02:31:58Z", "generation": 2, "labels": {"app": "jenkins"}, "name": "jenkins", "namespace": "pipeline-delivery", "resourceVersion": "613881", "selfLink": "/oapi/v1/namespaces/pipeline-delivery/deploymentconfigs/jenkins", "uid": "60020b63-966d-11e6-b719-fa163ed5c797"}, "spec": {"replicas": 1, "selector": {"app": "jenkins", "deploymentconfig": "jenkins"}, "strategy": {"resources": {}, "rollingParams": {"intervalSeconds": 1, "maxSurge": "25%", "maxUnavailable": "25%", "timeoutSeconds": 600, "updatePeriodSeconds": 1}, "type": "Rolling"}, "template": {"metadata": {"annotations": {"openshift.io/container.jenkins.image.entrypoint": "[\"/usr/libexec/s2i/run\"]", "openshift.io/generated-by": "OpenShiftNewApp"}, "creationTimestamp": null, "labels": {"app": "jenkins", "deploymentconfig": "jenkins"}}, "spec": {"containers": [{"env": [{"name": "JAVA_OPTS", "value": "-Djavax.net.ssl.trustStore=/etc/pipeline-delivery-env/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"}, {"name": "JENKINS_OPTS", "value": "--httpPort=-1 --httpsPort=8443 --httpsCertificate=/etc/pipeline-delivery-env/certs/jenkins.core.rht-labs.com/jenkins.core.rht-labs.com.crt --httpsPrivateKey=/etc/pipeline-delivery-env/certs/jenkins.core.rht-labs.com/jenkins.core.rht-labs.com.key"}, {"name": "JENKINS_PASSWORD", "value": "r3dh4t1!"}], "image": "172.30.103.3:5000/pipeline-delivery/jenkins@sha256:424a6ac0122fd097e1eedd9bddf6ccaf9334758fc8b38025ad421651155937ef", "imagePullPolicy": "Always", "name": "jenkins", "ports": [{"containerPort": 50000, "protocol": "TCP"}, {"containerPort": 8080, "protocol": "TCP"}], "resources": {}, "terminationMessagePath": "/dev/termination-log", "volumeMounts": [{"mountPath": "/var/lib/jenkins", "name": "jenkins-volume-1"}]}], "dnsPolicy": "ClusterFirst", "restartPolicy": "Always", "securityContext": {}, "terminationGracePeriodSeconds": 30, "volumes": [{"emptyDir": {}, "name": "jenkins-volume-1"}]}}, "test": false, "triggers": [{"type": "ConfigChange"}, {"imageChangeParams": {"automatic": true, "containerNames": ["jenkins"], "from": {"kind": "ImageStreamTag", "name": "jenkins:latest", "namespace": "pipeline-delivery"}, "lastTriggeredImage": "172.30.103.3:5000/pipeline-delivery/jenkins@sha256:424a6ac0122fd097e1eedd9bddf6ccaf9334758fc8b38025ad421651155937ef"}, "type": "ImageChange"}]}, "status": {"details": {"causes": [{"imageTrigger": {"from": {"kind": "ImageStreamTag", "name": "jenkins:latest", "namespace": "pipeline-delivery"}}, "type": "ImageChange"}], "message": "caused by an image change"}, "latestVersion": 1, "observedGeneration": 2}}}, "changed": false}

TASK [create-openshift-resources : Attempt to Apply New Port Specs to Deployment Config] ***
ok: [localhost] => {"ansible_facts": {"deployment_config": {"apiVersion": "v1", "kind": "DeploymentConfig", "metadata": {"annotations": {"openshift.io/generated-by": "OpenShiftNewApp"}, "creationTimestamp": "2016-10-20T02:31:58Z", "generation": 2, "labels": {"app": "jenkins"}, "name": "jenkins", "namespace": "pipeline-delivery", "resourceVersion": "613881", "selfLink": "/oapi/v1/namespaces/pipeline-delivery/deploymentconfigs/jenkins", "uid": "60020b63-966d-11e6-b719-fa163ed5c797"}, "spec": {"replicas": 1, "selector": {"app": "jenkins", "deploymentconfig": "jenkins"}, "strategy": {"resources": {}, "rollingParams": {"intervalSeconds": 1, "maxSurge": "25%", "maxUnavailable": "25%", "timeoutSeconds": 600, "updatePeriodSeconds": 1}, "type": "Rolling"}, "template": {"metadata": {"annotations": {"openshift.io/container.jenkins.image.entrypoint": "[\"/usr/libexec/s2i/run\"]", "openshift.io/generated-by": "OpenShiftNewApp"}, "creationTimestamp": null, "labels": {"app": "jenkins", "deploymentconfig": "jenkins"}}, "spec": {"containers": [{"env": [{"name": "JAVA_OPTS", "value": "-Djavax.net.ssl.trustStore=/etc/pipeline-delivery-env/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"}, {"name": "JENKINS_OPTS", "value": "--httpPort=-1 --httpsPort=8443 --httpsCertificate=/etc/pipeline-delivery-env/certs/jenkins.core.rht-labs.com/jenkins.core.rht-labs.com.crt --httpsPrivateKey=/etc/pipeline-delivery-env/certs/jenkins.core.rht-labs.com/jenkins.core.rht-labs.com.key"}, {"name": "JENKINS_PASSWORD", "value": "r3dh4t1!"}], "image": "172.30.103.3:5000/pipeline-delivery/jenkins@sha256:424a6ac0122fd097e1eedd9bddf6ccaf9334758fc8b38025ad421651155937ef", "imagePullPolicy": "Always", "name": "jenkins", "ports": [{"containerPort": 8443, "protocol": "TCP"}, {"containerPort": 50000, "protocol": "TCP"}], "resources": {}, "terminationMessagePath": "/dev/termination-log", "volumeMounts": [{"mountPath": "/var/lib/jenkins", "name": "jenkins-volume-1"}]}], "dnsPolicy": "ClusterFirst", "restartPolicy": "Always", "securityContext": {}, "terminationGracePeriodSeconds": 30, "volumes": [{"emptyDir": {}, "name": "jenkins-volume-1"}]}}, "test": false, "triggers": [{"type": "ConfigChange"}, {"imageChangeParams": {"automatic": true, "containerNames": ["jenkins"], "from": {"kind": "ImageStreamTag", "name": "jenkins:latest", "namespace": "pipeline-delivery"}, "lastTriggeredImage": "172.30.103.3:5000/pipeline-delivery/jenkins@sha256:424a6ac0122fd097e1eedd9bddf6ccaf9334758fc8b38025ad421651155937ef"}, "type": "ImageChange"}]}, "status": {"details": {"causes": [{"imageTrigger": {"from": {"kind": "ImageStreamTag", "name": "jenkins:latest", "namespace": "pipeline-delivery"}}, "type": "ImageChange"}], "message": "caused by an image change"}, "latestVersion": 1, "observedGeneration": 2}}}, "changed": false}

TASK [create-openshift-resources : Set Fact for Required Deployment Config Updates] ***
ok: [localhost] => {"ansible_facts": {"update_to_dc_required": true}, "changed": false}

TASK [create-openshift-resources : Use a unique temporary file to store the Deployment Config object] ***
changed: [localhost] => {"changed": true, "cmd": ["mktemp"], "delta": "0:00:00.002014", "end": "2016-10-19 22:32:04.911645", "rc": 0, "start": "2016-10-19 22:32:04.909631", "stderr": "", "stdout": "/tmp/tmp.tQWRm2WHfx", "stdout_lines": ["/tmp/tmp.tQWRm2WHfx"], "warnings": []}

TASK [create-openshift-resources : Prepare the object definition for the Deployment Config] ***
changed: [localhost] => {"changed": true, "checksum": "98ce63e4eff740f125ea94558372e715c35b5955", "dest": "/tmp/tmp.tQWRm2WHfx", "gid": 352000006, "group": "obedin", "md5sum": "6e8d464bec07ad8287a3e42f82797e64", "mode": "0600", "owner": "obedin", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 2735, "src": "/home/obedin/.ansible/tmp/ansible-tmp-1476930725.13-106230250392241/source", "state": "file", "uid": 352000006}

TASK [create-openshift-resources : Apply New Deployment Config] ****************
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (12 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (11 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (10 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (9 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (8 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (7 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (6 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (5 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (4 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (3 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (2 retries left).
FAILED - RETRYING: TASK: create-openshift-resources : Apply New Deployment Config (1 retries left).
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["oc", "replace", "dc", "jenkins", "-f", "/tmp/tmp.tQWRm2WHfx", "-n", "pipeline-delivery"], "delta": "0:00:00.131760", "end": "2016-10-19 22:33:09.171410", "failed": true, "rc": 1, "start": "2016-10-19 22:33:09.039650", "stderr": "Error from server: error when replacing \"/tmp/tmp.tQWRm2WHfx\": Operation cannot be fulfilled on deploymentconfigs \"jenkins\": the object has been modified; please apply your changes to the latest version and try again", "stdout": "", "stdout_lines": [], "warnings": []}
    to retry, use: --limit @load_infra.retry

PLAY RECAP *********************************************************************
localhost                  : ok=209  changed=39   unreachable=0    failed=1   
```

**Comment by oybed** [comment]
Overall it seems to be doing what we'd want it to do as re-running applies the changes, but I wonder if the above error is one of those race conditions you have mentioned.

**Comment by sherl0cks** [comment]
Yes, its the race condition. I've added a retry via recursive inclusion of the task. This could result in an infinite loop. See #45

**Comment by oybed** [comment]
Latest change looks to be a winner - will merge.

**Pull request merged**
