### PR TITLE
Adding ability to add labels to projects

### PR DESCRIPTION
**Pull request by etsauer**
#### What does this PR do?
uses `oc label ns/{{ project.name }}` to add labels to projects.

#### Which tests illustrate how this code works?
roles/create-openshift-resources/tests/vars/openshift_resources.json

#### Is there a relevant Issue open for this?
n/a

#### Are there any other relevant resources that should be reviewed as well?
n/a

#### Who would you like to review this?
/cc @sherl0cks @oybed

### CODE REVIEW

**Comment by oybed** [comment]
@etsauer We already have some support for labels, any chance that can be enhanced rather than doing this in parallel? i.e.: look at the existing labels for apps implementation:

A few resources to look at:
https://github.com/rht-labs/ansible-stacks/blob/master/roles/create-openshift-resources/tasks/create_labels_string.yml

https://github.com/rht-labs/ansible-stacks/blob/master/roles/create-openshift-resources/tasks/create_app.yml#L72-L85

**Comment by etsauer** [comment]
@oybed that's adding a label to an app in oc new-app. I have the need to put labels on namespaces in order to group projects together.

**Comment by oybed** [comment]
Understood, but I think it could be generalized a bit more and have some common functionality to avoid confusion. Anyway, we can discuss more details offline.

**Comment by sherl0cks** [comment]
@etsauer general note on key / value pairs in this repo: please model them as a map instead of a complex object. This is done currently in the API with [Application.labels](https://github.com/rht-labs/api-design/blob/master/swagger.yaml#L1289). For example:

``` json
"project" : {
  "name" : "foo",
  "labels" :  {
     "key1" : "value1",
     "key2" : "value2"
  }
}
```

I'll try to find a few moments to talk through this with @oybed tomorrow

**Comment by etsauer** [comment]
@oybed @sherl0cks I've refactored to a model that looks more like what you're asking, and used the app labels as a reference, however I can't get ansible to understand this data structure. See the changes i've made and please advise. Is there a test that shows labels being added to an app that I can use as a reference?

**Comment by sherl0cks** [comment]
@etsauer we do this for app level labels today. https://github.com/rht-labs/ansible-stacks/blob/master/roles/create-openshift-resources/tasks/create_labels_string.yml#L9

**Comment by etsauer** [comment]
@oybed @sherl0cks ok, got it working. Please review now. Also i'm testing with:

```
ansible-playbook -i roles/create-openshift-resources/tests/inventory roles/create-openshift-resources/tests/cdk_create_openshift_resources.yml --private-key=~/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/private_key -e "cleanup=yes"
```

**Comment by oybed** [comment]
The code looks ok, but I think there's a higher level architecture discussion that should happen around labels - i.e.: what I mentioned before re: existing label functionality. The way we are headed now, it seems that we will get a custom way to handle labels for every piece we want to support setting labels for, so would like to align these implementations more and have re-use of functionality. I suspect we don't have much time to have this discussion at this point, however, so it may just be best to merge as-is, write up an issue for it and we can re-visit when we find some time.

**Comment by etsauer** [comment]
@oybed yeah i tried to at least copy the structure used for apps as much as possible, however the way the current code applies labels to apps uses a `--labels` syntax that isn't available to `oc new-project`, so i couldn't re-use as-is. The only thing i could think of to further standardize, is to use `oc label` to apply labels to all resources post-creation, but i wasn't sure if you wanted to do that for apps.

**Comment by sherl0cks** [comment]
@etsauer I'm ok using `oc label` post object creation if it unified implementation.

**Comment by etsauer** [comment]
@sherl0cks thinking about it more... if I were you I wouldn't do `oc label` after the fact for app stuff, because if you're running `oc new-app` to create stuff, you could end up creating multiple resources and the labels would go on all of them. It would be pretty tricky to go back and find those resources afterwards to label them

**Comment by etsauer** [comment]
@oybed @sherl0cks FYI, this PR needs merged before the other two currently open, because this once contains the fixes to the `cdk_create_openshift_resources` test

**Pull request closed without merging**
