### PR TITLE
Ability to auth with a token

### PR DESCRIPTION
**Pull request by etsauer**
#### What does this PR do?
Adds this ability to authenticate with a service account token rather than a username and password. I expect there will be a lot to discuss on the implementation, 

#### Which tests illustrate how this code works?
test in progress, wanted to get the PR open.

#### Is there a relevant Issue open for this?
n/a

#### Are there any other relevant resources that should be reviewed as well?
https://docs.openshift.com/container-platform/3.3/dev_guide/service_accounts.html

#### Who would you like to review this?
/cc @oybed @sherl0cks

### CODE REVIEW

**Comment by oybed** [comment]
@etsauer already had this in the works (just pushed a [branch up](https://github.com/oybed/ansible-stacks/tree/token)), but will review and see what we have in common and potentially merge yours first, then merge my changes on top. ... I'll let you know.

**Comment by etsauer** [comment]
@oybed another thought I had was that it would be good to be able to simply
skip the login, maybe with an option to use the current login. We are
working on setting up a Jenkins server in a pod to run stacks jobs, and in
that case the pod comes with an active kubeconfig, so we also need the
ability to just use it. Does it make sense to add this option to this PR?

**Comment by oybed** [comment]
@etsauer I like it - something we have though of as well, and your use case shows the real need for it. If you don't mind working it in to this PR, that would be great, if not we can do a follow-up PR.

**Comment by etsauer** [comment]
@oybed all functionality is there, but i'm having some trouble with the test of the token. could you take a look at what i'm trying to do and see if you have any other ideas?

**Comment by oybed** [comment]
@etsauer I checked the code and it appears that the many conditional checking in the `configure_openshift_cluster.yml` file is having some issues. A couple of things: Using True/False seems to be problematic (I think partially due to the changes in Ansible 2.2), and there's also a mixture of quoted and non-quoted True/False conditions (which can also be a problem). Also, on line 51, I believe you meant to check for `oc_login == false`. Anyway; when I made some changes to the above mentioned findings, I was able to make it work with your test. Hence, the token is getting obtained correctly and passed in to the role, it just doesn't get added as the conditions are wrong, or evaluated by ansible wrong rather.

It's getting late, but I'll take a closer look tomorrow to see if I can assist with cleaning up the login in `configure_openshift_cluster.yml` as some of that is old code and seems to be having issues.

**Comment by etsauer** [comment]
@oybed try this out.

**Comment by oybed** [comment]
LGTM - will merge and move tests in a follow-up PR

**Pull request merged**
