### PR TITLE
Adding ability to create an app by instantiating a template

### PR DESCRIPTION
**Pull request by etsauer**
#### What does this PR do?
Allows a template to be instantiated within create_openshift_resources role.

#### Which tests illustrate how this code works?
`roles/create-openshift-resources/tests/cdk_create_openshift_resources.yml`

#### Is there a relevant Issue open for this?
n/a

#### Are there any other relevant resources that should be reviewed as well?
n/a

#### Who would you like to review this?
/cc @oybed @sherl0cks

### CODE REVIEW

**Comment by etsauer** [comment]
bump.

**Comment by sherl0cks** [comment]
@etsauer thanks for this. I like the idea here. One question:

1. The implementation assumes that the template already exists as an OpenShift API object. Is this an acceptable assumption? Generally speaking, we add features that are end to end automated i.e. you should be able to create cluster A, configure cluster A, destroy cluster A, create cluster B, run ansible-stacks with the  automation api object describing cluster A and then have the same state in cluster B as was in cluster A. 

This current PR wouldn't support the above workflow because any custom template (which I'm assuming is a key use case) would need to manually added to the cluster before running this automation. Are you OK with that? Would it be hard to write the automation to add the template object to OpenShift?

2. Can you add a separate test for templates? You're piggy backing on an existing test which can make it hard to understand failures. Lemme know if you need support here. Small note, `project.environment_type` should be `build` or `promotion`.

**Comment by etsauer** [comment]
@sherl0cks the way I see it, the instantiation of some template and the creation of that template in your cluster are independent actions, generally taken by different roles/users. Additionally, openshift's installer provides methods for pre-loading a set of templates (default or custom) at install time, so I would mostly want to depend on that.

**Comment by sherl0cks** [comment]
@etsauer OK - we can work with that. I'd still like to have the that test updated, but in the spirit of collaboration here, I'm going to merge this PR and then share with you a follow up on how I'd the test to look

**Pull request merged**
